package com.ylink.inetpay.cbs.chl.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.ylinkpay.framework.mybatis.annotation.MybatisMapper;

import com.ylink.inetpay.common.core.constant.EChlChannelCode;
import com.ylink.inetpay.common.core.constant.EChlOrCheckFile;
import com.ylink.inetpay.common.project.channel.dto.TbChlChannel;
import com.ylink.inetpay.common.project.channel.dto.TbChlPayStyle;
@MybatisMapper("tbChlChannelMapper")
public interface TbChlChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_CHANNEL
     *
     * @mbggenerated Sat Nov 12 11:25:23 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_CHANNEL
     *
     * @mbggenerated Sat Nov 12 11:25:23 CST 2016
     */
    int insert(TbChlChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_CHANNEL
     *
     * @mbggenerated Sat Nov 12 11:25:23 CST 2016
     */
    int insertSelective(TbChlChannel record);
    /**
	 * 查询所有需要下载对账文件的渠道信息（有对账文件）
	 * @return
	 * @throws CbsCheckedException
	 */
    List<TbChlChannel> getChannels(@Param("orCheckFile")EChlOrCheckFile joinBank);
	
    TbChlChannel selectByPrimaryKey(String id);
    
    int updateByPrimaryKeySelective(TbChlChannel record);

    int updateByPrimaryKey(TbChlChannel record);
    
    int updateByChannelCode(TbChlChannel record);
    
    List<TbChlChannel> selectByDto(TbChlChannel record);
    
    TbChlChannel selectByChannelCode(EChlChannelCode channelCode);
    /**分页查询 **/
    List<TbChlChannel> findListPage(TbChlChannel record);
    /** 获取支付方式**/
    List<TbChlPayStyle> getPayStyle();
    
    /** 获取手机快捷支付方式**/
    List<TbChlPayStyle> getMobileFastStyle();
    
}