package com.ylink.inetpay.cbs.chl.dao;

import java.util.List;

import org.ylinkpay.framework.mybatis.annotation.MybatisMapper;

import com.ylink.inetpay.common.project.channel.dto.TbChlBindBankCard;
@MybatisMapper("tbChlBindBankCardMapper")
public interface TbChlBindBankCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_BIND_BANK_CARD
     *
     * @mbggenerated Sat Nov 12 11:26:14 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_BIND_BANK_CARD
     *
     * @mbggenerated Sat Nov 12 11:26:14 CST 2016
     */
    int insert(TbChlBindBankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_BIND_BANK_CARD
     *
     * @mbggenerated Sat Nov 12 11:26:14 CST 2016
     */
    int insertSelective(TbChlBindBankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_BIND_BANK_CARD
     *
     * @mbggenerated Sat Nov 12 11:26:14 CST 2016
     */
    TbChlBindBankCard selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_BIND_BANK_CARD
     *
     * @mbggenerated Sat Nov 12 11:26:14 CST 2016
     */
    int updateByPrimaryKeySelective(TbChlBindBankCard record);

    
    int updateByPrimaryKey(TbChlBindBankCard record);
    
    List<TbChlBindBankCard> selectByParam(TbChlBindBankCard record);

	List<TbChlBindBankCard> list(TbChlBindBankCard searchDto);
}