package com.ylink.inetpay.cbs.chl.dao;

import java.util.List;

import org.ylinkpay.framework.mybatis.annotation.MybatisMapper;

import com.ylink.inetpay.common.project.channel.dto.TbChlChannelRoute;
@MybatisMapper("tbChlChannelRouteMapper")
public interface TbChlChannelRouteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_CHANNEL_ROUTE
     *
     * @mbggenerated Sat Nov 12 11:25:23 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_CHANNEL_ROUTE
     *
     * @mbggenerated Sat Nov 12 11:25:23 CST 2016
     */
    int insert(TbChlChannelRoute record);

    int insertSelective(TbChlChannelRoute record);

    TbChlChannelRoute selectByPrimaryKey(String id);

    int updateByPrimaryKeySelective(TbChlChannelRoute record);

    int updateByPrimaryKey(TbChlChannelRoute record);
    /**集合查询 **/
    List<TbChlChannelRoute> findListPage(TbChlChannelRoute record);
    
    List<TbChlChannelRoute> findRouteByPayOreder(Long payOrder);

}