package com.ylink.inetpay.cbs.chl.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.ylinkpay.framework.mybatis.annotation.MybatisMapper;

import com.ylink.inetpay.common.project.channel.dto.TbChlBankCode;

@MybatisMapper("tbChlBanCodeMapper")
public interface TbChlBankCodeMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table TB_CHL_BANKCODE
	 *
	 * @mbggenerated Sat Nov 12 16:12:37 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table TB_CHL_BANKCODE
	 *
	 * @mbggenerated Sat Nov 12 16:12:37 CST 2016
	 */
	int insert(TbChlBankCode record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table TB_CHL_BANKCODE
	 *
	 * @mbggenerated Sat Nov 12 16:12:37 CST 2016
	 */
	int insertSelective(TbChlBankCode record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table TB_CHL_BANKCODE
	 *
	 * @mbggenerated Sat Nov 12 16:12:37 CST 2016
	 */
	TbChlBankCode selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table TB_CHL_BANKCODE
	 *
	 * @mbggenerated Sat Nov 12 16:12:37 CST 2016
	 */
	int updateByPrimaryKeySelective(TbChlBankCode record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table TB_CHL_BANKCODE
	 *
	 * @mbggenerated Sat Nov 12 16:12:37 CST 2016
	 */
	int updateByPrimaryKey(TbChlBankCode record);

	List<TbChlBankCode> findListPage(TbChlBankCode bankCode);

	/**
	 * 查询银行相关
	 * @param bankCode
	 * @return
	 */
	public List<TbChlBankCode> getList(TbChlBankCode bankCode);

	List<TbChlBankCode> getDepositBankCode(@Param("cityCode")String cityCode, @Param("bankType")String bankType);
	/**
	 * 根据银行行号获取银行名称
	 * @param innerAccountBankcode
	 * @return
	 */
	List<TbChlBankCode> findBankNameByBankCode(String bankCode);
	
	/**
	 * 根据银行行名获取银行
	 * @param bankName
	 * @return
	 */
	List<TbChlBankCode> findBankByBankName(String bankName);
	/**
	 * 根据银行行号获取银行信息
	 * @param payeeBankCodes
	 * @return
	 */
	List<TbChlBankCode> findBankCodes(@Param("bankCodes")List<String> bankCodes);
	/**
	 * 根据银行名称，模糊查询获取bankcode集合
	 * @param payeeBankTypeName
	 * @return
	 */
	List<TbChlBankCode> findBankCodeByBankName(String bankName);
	/**
	 * 获取所有银行信息
	 * @return
	 */
	List<TbChlBankCode> findChlBankCodeList();
	/**
	 * 根据银行名称查询银行列表
	 */
	List<TbChlBankCode> findChlBankCodeMapByBankNames(@Param("bankNames")List<String> bankNames);
	/**
	 * 根据bankType分组,取每一组的第一条数据
	 * @return
	 */
	List<TbChlBankCode> findChlBankMapGroupByBankType();

}