package com.ylink.inetpay.cbs.chl.dao;

import java.util.List;

import org.ylinkpay.framework.mybatis.annotation.MybatisMapper;

import com.ylink.inetpay.common.project.channel.dto.TbChlTransferOrder;
@MybatisMapper("tbChlTransferOrderMapper")
public interface TbChlTransferOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_TRANSFER_ORDER
     *
     * @mbggenerated Sat Nov 12 11:25:23 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_TRANSFER_ORDER
     *
     * @mbggenerated Sat Nov 12 11:25:23 CST 2016
     */
    int insert(TbChlTransferOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_TRANSFER_ORDER
     *
     * @mbggenerated Sat Nov 12 11:25:23 CST 2016
     */
    int insertSelective(TbChlTransferOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_TRANSFER_ORDER
     *
     * @mbggenerated Sat Nov 12 11:25:23 CST 2016
     */
    TbChlTransferOrder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_TRANSFER_ORDER
     *
     * @mbggenerated Sat Nov 12 11:25:23 CST 2016
     */
    int updateByPrimaryKeySelective(TbChlTransferOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_TRANSFER_ORDER
     *
     * @mbggenerated Sat Nov 12 11:25:23 CST 2016
     */
    int updateByPrimaryKey(TbChlTransferOrder record);
    
    TbChlTransferOrder selectByPayId(String payId);
    
    TbChlTransferOrder selectByPlatNo(String platNo);
    
    List<TbChlTransferOrder> findListPage(TbChlTransferOrder record);
}