package com.ylink.inetpay.cbs.chl.dao;

import java.util.List;

import org.ylinkpay.framework.mybatis.annotation.MybatisMapper;

import com.ylink.inetpay.common.project.channel.dto.TbChlAccChangeFileRecord;

@MybatisMapper("tbChlAccChangeFileRecordMapper")
public interface TbChlAccChangeFileRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_ACCCHANGE_FILE _RECORD
     *
     * @mbggenerated Wed Dec 07 21:24:56 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_ACCCHANGE_FILE _RECORD
     *
     * @mbggenerated Wed Dec 07 21:24:56 CST 2016
     */
    int insert(TbChlAccChangeFileRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_ACCCHANGE_FILE _RECORD
     *
     * @mbggenerated Wed Dec 07 21:24:56 CST 2016
     */
    int insertSelective(TbChlAccChangeFileRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_ACCCHANGE_FILE _RECORD
     *
     * @mbggenerated Wed Dec 07 21:24:56 CST 2016
     */
    TbChlAccChangeFileRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_ACCCHANGE_FILE _RECORD
     *
     * @mbggenerated Wed Dec 07 21:24:56 CST 2016
     */
    int updateByPrimaryKeySelective(TbChlAccChangeFileRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_ACCCHANGE_FILE _RECORD
     *
     * @mbggenerated Wed Dec 07 21:24:56 CST 2016
     */
    int updateByPrimaryKey(TbChlAccChangeFileRecord record);
    
    /**
     * 批量插入
     * @param list
     * @return
     */
    int batchInsert(List<TbChlAccChangeFileRecord> list);
    
    /**
     * 根据渠道编码和下载日期锁表查询
     * @param channelCode 渠道编码
     * @param downloadDate 
     * @return
     */
    TbChlAccChangeFileRecord lockSelectByParam(String channelCode,String downloadDate);
    
    /**
     * 根据下载日期查询未处理和处理失败的动账文件记录
     * @param downloadDate
     * @return
     */
    List<TbChlAccChangeFileRecord> selectAccChangeFileRecordByDownloadDate(String downloadDate);
    
    /**
     * 根据参数查询所有数据
     * @param PayPaymentDto
     * @return
     */
    List<TbChlAccChangeFileRecord> queryAllData(TbChlAccChangeFileRecord record);
}