package com.ylink.inetpay.cbs.chl.dao;

import java.util.List;

import org.ylinkpay.framework.core.model.PageData;
import org.ylinkpay.framework.mybatis.annotation.MybatisMapper;

import com.ylink.inetpay.common.project.channel.dto.TbChlCardBin;
@MybatisMapper("tbChlCardBinMapper")
public interface TbChlCardBinMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_CARD_BIN
     *
     * @mbggenerated Sat Nov 12 16:12:37 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_CARD_BIN
     *
     * @mbggenerated Sat Nov 12 16:12:37 CST 2016
     */
    int insert(TbChlCardBin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_CARD_BIN
     *
     * @mbggenerated Sat Nov 12 16:12:37 CST 2016
     */
    int insertSelective(TbChlCardBin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_CARD_BIN
     *
     * @mbggenerated Sat Nov 12 16:12:37 CST 2016
     */
    TbChlCardBin selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_CARD_BIN
     *
     * @mbggenerated Sat Nov 12 16:12:37 CST 2016
     */
    int updateByPrimaryKeySelective(TbChlCardBin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_CARD_BIN
     *
     * @mbggenerated Sat Nov 12 16:12:37 CST 2016
     */
    int updateByPrimaryKey(TbChlCardBin record);
    /**分页查询 **/
    List<TbChlCardBin> findListPage(TbChlCardBin record);
    
    public List<TbChlCardBin> getCardBinByCardSign(String CardSign);
}