package com.ylink.inetpay.cbs.chl.dao;

import org.ylinkpay.framework.mybatis.annotation.MybatisMapper;

import com.ylink.inetpay.common.project.channel.dto.TbChlFrontendBusiMapping;

@MybatisMapper("tbChlFrontendBusiMappingMapper")
public interface TbChlFrontendBusiMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_FRONTEND_BUSI_MAPPING
     *
     * @mbggenerated Mon Dec 12 18:02:18 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_FRONTEND_BUSI_MAPPING
     *
     * @mbggenerated Mon Dec 12 18:02:18 CST 2016
     */
    int insert(TbChlFrontendBusiMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_FRONTEND_BUSI_MAPPING
     *
     * @mbggenerated Mon Dec 12 18:02:18 CST 2016
     */
    int insertSelective(TbChlFrontendBusiMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_FRONTEND_BUSI_MAPPING
     *
     * @mbggenerated Mon Dec 12 18:02:18 CST 2016
     */
    TbChlFrontendBusiMapping selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_FRONTEND_BUSI_MAPPING
     *
     * @mbggenerated Mon Dec 12 18:02:18 CST 2016
     */
    int updateByPrimaryKeySelective(TbChlFrontendBusiMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_FRONTEND_BUSI_MAPPING
     *
     * @mbggenerated Mon Dec 12 18:02:18 CST 2016
     */
    int updateByPrimaryKey(TbChlFrontendBusiMapping record);
    
    /**
     * 根据对象查询
     * @param record
     * @return
     */
    TbChlFrontendBusiMapping selectByParam(TbChlFrontendBusiMapping record);
}