package com.ylink.inetpay.cbs.chl.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.ylinkpay.framework.mybatis.annotation.MybatisMapper;

import com.ylink.inetpay.common.project.channel.dto.TbChlBankAccount;
@MybatisMapper("tbChlBankAccountMapper")
public interface TbChlBankAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_BANK_ACCOUNT
     *
     * @mbggenerated Sat Nov 12 11:25:23 CST 2016
     */
    int deleteByPrimaryKey(String id);

  
    int insert(TbChlBankAccount record);

   
    int insertSelective(TbChlBankAccount record);

  
    TbChlBankAccount selectByPrimaryKey(String id);
    /** **/
    TbChlBankAccount findByChannelCode(@Param("channelCode")String channelCode);
    /**分页查询 **/
    List<TbChlBankAccount> findListPage(TbChlBankAccount record);
    
    int updateByPrimaryKeySelective(TbChlBankAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHL_BANK_ACCOUNT
     *
     * @mbggenerated Sat Nov 12 11:25:23 CST 2016
     */
    int updateByPrimaryKey(TbChlBankAccount record);

    /**
     * 根据用户编号获取用户银行列表
     * @param userId
     * @return
     */
	List<TbChlBankAccount> getUserBankAccList();

	/**
	 * 根据银行卡号获取银行信息
	 * @param goldBankAccNo
	 * @return
	 */
	TbChlBankAccount getChlBankAccount(String goldBankAccNo);

	/**
	 * 根据银行行号获取银行列表信息
	 * @param goldBankCode
	 * @return
	 */
	List<TbChlBankAccount> chlBankService(String goldBankType);

	/**
	 * 根据出金人
	 * @param outerAcct
	 * @return
	 */
	TbChlBankAccount findByBankAccNo(String outerAcct);

	/**
	 * 获取平台所有银行卡信息
	 * @return
	 */
	List<TbChlBankAccount> getBankAccNoList();

	/**
	 * 获取系统银行类型
	 * @return
	 */
	List<TbChlBankAccount> getBankTypes();
 
	/**
	 * 获取渠道信息
	 * @return
	 */
	List<TbChlBankAccount> findTbChlBankAccount();
 

	/**
	 * 批量平台对外支付获取有分之行名称的平台银行账户信息
	 * @return
	 */
	List<TbChlBankAccount> getBatchExpBankAccount();
 
}